### ISSUE TITLE
Mobile UI Revise

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1360]
![image](https://cloud.githubusercontent.com/assets/2804889/11430138/bc625dfa-948a-11e5-988d-914dedcebb7c.png)

**Comment by beyzakokcan** [comment]
Actually all entity pages should be revised for different devices

**Comment by behramcelen** [comment]
workflow page mobile revise can be imposible. There is a lot buttons, text and descriptions

**Comment by hmert** [comment]
nothing is impossible with me
