### ISSUE TITLE
Symfony applications should not throw AccessDeniedHttpException

### ISSUE THREAD

**Issue by utkuaydin** [ojs/ojs#1369]
`AccessDeniedHttpException`s are thrown inside controllers and most of them are in ApiBundle ones. SensioLabs Insight suggests that `AccessDeniedException`s should be thrown instead.

**Comment by behramcelen** [comment]
if exists can add SensioLabs Insight link

**Comment by behramcelen** [comment]
related pr https://github.com/ojs/ojs/pull/1399
