### ISSUE TITLE
Search Query bug

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1388]
The query should be `and` , I've selected "İstanbul Tıp Dergisi" and "Journal Manager"
http://beta.dergipark.gov.tr/people?journal_filters=%C4%B0stanbul+T%C4%B1p+Fak%C3%BCltesi+Dergisi&role_filters=ROLE_JOURNAL_MANAGER

![image](https://cloud.githubusercontent.com/assets/182906/12018383/7e6c1650-ad6a-11e5-806f-6c4648e40408.png)

**Comment by behramcelen** [comment]
if we try use this issue logic. This causes many other issues;
 - when only role selected.
 - when only journal selected.
 - when both selected
 - when multiple select
 - ...

**Comment by behramcelen** [comment]
we can close this issue directly :+1:

**Comment by utkuaydin** [comment]
Yes, it isn't sensible to pinpoint an user who has a role only in a specified journal using filters on the left column. Changing filters in order to achieve that only would make filters more confusing to the end user. I'd say we can close this too, if everyone agrees.
