### ISSUE TITLE
PHPUnit TESTs Revise

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1391]
Our test are simply failing.

All tests should be revised with proper methods.

---
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=29717795)](https://www.bountysource.com/issues/29717795-phpunit-tests-revise?utm_source=29717795&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by hmert** [comment]
https://github.com/ojs/ojs/pull/1516

**Comment by hmert** [comment]
🎉  congratulations @yazbahar

**Comment by yazbahar** [comment]
thank you @hmert
