### ISSUE TITLE
Translatable entities grid filter problem

### ISSUE THREAD

**Issue by behramcelen** [ojs/ojs#1402]

**Comment by behramcelen** [comment]
There are 2 solving option for this problem;
option 1 - Expose with translatable fields for all locales;
![image](https://cloud.githubusercontent.com/assets/4572080/12597751/356ef0d0-c48f-11e5-838c-e0ce2eed2f79.png)

option 2 - Expose only first field of object translations;
![image](https://cloud.githubusercontent.com/assets/4572080/12597812/6ec056d0-c48f-11e5-9e5b-ffeb562acf8e.png)

Option 1 is easy way. but option 2 is more logical and useful we must use some tricks.
I will support examples with new branch commits.

**Comment by behramcelen** [comment]
option 1 changes commit -> https://github.com/ojs/ojs/commit/983896e28438f96d667fd9e4583f0225bdabdb85
option 2 changes commit -> https://github.com/ojs/ojs/commit/5697166d528c13ff8af7537f15677c5c2abf5457

**Comment by behramcelen** [comment]
related branch https://github.com/ojs/ojs/tree/iss1402

**Comment by hmert** [comment]
Let's combine with n translations in a cell.

**Comment by behramcelen** [comment]
@hmert great idea. We did option 3 like below and works perfectly :tada: 
![image](https://cloud.githubusercontent.com/assets/4572080/12608979/d6022924-c4e7-11e5-93c5-42fd6c5c12a2.png)

**Comment by behramcelen** [comment]
i will supply for all like journal entities

**Comment by behramcelen** [comment]
i will apply to article entity lastly
