### ISSUE TITLE
Statistics Page Performance Issue

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1403]

**Comment by behramcelen** [comment]
Related commits;
https://github.com/ojs/ojs/commit/1b7ed67d15dfebe8f7219441564347b71c1c2046
https://github.com/ojs/ojs/commit/7fadb1650052089560a1d305c8de328df8548ef1

**Comment by behramcelen** [comment]
we using cache system for this page. I written an command like cache:admin:static. Command runs in 80 minutes this is an problem but i will revise code. For now i am closing this issue
