### ISSUE TITLE
Refactor SiteBundle's SiteController

### ISSUE THREAD

**Issue by utkuaydin** [ojs/ojs#1413]
`SiteController` has too many actions and we need to move some of them to their own controllers.

| SiteController action   | New controller       |
|-------------------------|----------------------|
| archiveIndexAction      | JournalController    |
| journalBoardAction      | JournalController    |
| journalContactsAction   | JournalController    |
| journalIndexAction      | JournalController    |
| lastArticlesIndexAction | JournalController    |
| subscribeAction         | JournalController    |
| announcementIndexAction | JournalCmsController |
| journalPageDetailAction | JournalCmsController |
| journalPostDetailAction | JournalCmsController |
| pageDetailAction        | CmsController        |
| postDetailAction        | CmsController        |
| issuePageAction         | IssueController      |
| journalArticlesAction   | ArticleController    |

**Comment by behramcelen** [comment]
i checked there is no problem. great job 👏  thanks @yazbahar 🙏
