### ISSUE TITLE
Exception thrown when using issue rest api

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1422]
Symfony logs the following exception while using /api/public/v1/doc#post--api-v1-journal-{journalId}-issues.{_format} endpoint.

> [2016-03-16 17:51:32] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "/var/www/html/ujs.localhost/web/uploads/issuefiles3DJqVE" to "/var/www/html/ujs.localhost/app/../web/uploads/issuefiles/"." at /var/www/html/ujs.localhost/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 280 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/var/www/html/ujs.localhost/web/uploads/issuefiles3DJqVE\" to \"/var/www/html/ujs.localhost/app/../web/uploads/issuefiles/\". at /var/www/html/ujs.localhost/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:280)"} []

I have checked directory permissions all files and directories under /web/uploads/ belongs to www-data and gave them 777 just in case. Exception continued so I tried adding ACL entries but it did not solve the problem.

I have noticed /web/uploads/issuefiles/ exists in the path so I traced the exception and found this line: https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Handler/JournalIssueHandler.php#L177

Exception occurs when $file['filename'] variable is set to null or empty string which is the case for me. 

I tried same request to beta server, I got the correct response on there. I think this bug may be caused by commits after beta server deployment.

**Comment by delirehberi** [comment]
Which version do you use @memduhcagridemir ?

**Comment by memduhcagridemir** [comment]
I checked out the repo a week ago. It was rest api v1 I think.

**Comment by memduhcagridemir** [comment]
Tried after pulling changes, Symfony throws the same exception.

> [2016-03-18 13:58:31] request.INFO: Matched route "api_1_post_issue". {"route_parameters":{"_controller":"Ojs\\ApiBundle\\Controller\\Journal\\JournalIssueRestController::postIssueAction","_format":"json","journalId":"11","_route":"api_1_post_issue"},"request_uri":"http://ujs.localhost/api/v1/journal/11/issues.json?apikey=MjZjYzhmYTE3OGIxYTEyMzI3ZDY3MDdiYzY5MjQ5MDM1NDVhOTg1ZQ%3D%3D"} []
> [2016-03-18 13:58:31] security.INFO: Attempting SimplePreAuthentication. {"key":"api","authenticator":"Ojs\\ApiBundle\\Security\\ApiKeyAuthenticator"} []
> [2016-03-18 13:58:31] security.DEBUG: ACL found, permission granted. Voting to grant access. [] []
> [2016-03-18 13:58:31] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Filesystem\Exception\IOException: "Cannot rename "/var/www/html/ujs.localhost/web/uploads/issuefilesW3HTlV" to "/var/www/html/ujs.localhost/app/../web/uploads/issuefiles/"." at /var/www/html/ujs.localhost/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php line 280 {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Cannot rename \"/var/www/html/ujs.localhost/web/uploads/issuefilesW3HTlV\" to \"/var/www/html/ujs.localhost/app/../web/uploads/issuefiles/\". at /var/www/html/ujs.localhost/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:280)"} []

**Comment by delirehberi** [comment]
can you try after checked out version [1.9](https://github.com/ojs/ojs/releases/tag/1.9)? i labeled this is a bug for master branch.

**Comment by utkuaydin** [comment]
Our deployment on dergipark.gov.tr is currently in sync with master and I am having no problem with that API endpoint. You don't need to checkout any other tag.

Could you paste more of your stack trace? I am having a hard time understanding why it tries to rename `web/uploads/issuefilesW3HTlV` to `web/uploads/issuefiles`.

**Comment by memduhcagridemir** [comment]
That was all of the stacktrace logged by Symfony. 

Could you please check the $file variable after request: https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Handler/JournalIssueHandler.php#L177

I think it may be the difference between requests we sent.

**Comment by utkuaydin** [comment]
Are you sure? Your stack trace doesn't tell which line made the call to `Filesystem.php:280`.

**Comment by memduhcagridemir** [comment]
I wasn't on dev environment. I switched to it and got this response: https://gist.github.com/memduhcagridemir/d52019edf1acb30887e1

**Comment by behramcelen** [comment]
i will check this issue on weekend days.

**Comment by memduhcagridemir** [comment]
I was posting the data as json before, today I tried posting it as formdata and problem solved. 

Interestingly, I can make the same json request to beta server and there is no error there. :+1:
