### ISSUE TITLE
Editorial board displayed as a list

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1433]
Not a profile based, but it should be a list.

**Comment by beyzakokcan** [comment]
EXAMPLES;
http://www.journals.elsevier.com/achievements-in-the-life-sciences/editorial-board/
http://www.springer.com/materials/special+types/journal/10971?detailsPage=editorialBoard

**Comment by behramcelen** [comment]
fixed with https://github.com/ojs/ojs/commit/51101e23be3cef9652389a672e2231aa14989184
