### ISSUE TITLE
emails of Members of Editorial board 

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1434]
editor /journal manager should be able to choose whether Members' email adresses should be public or not.

**Comment by hmert** [comment]
@beyzakokcan I think, it's not a good option for Editors. The member may not want to show his/her mail address to the public.

**Comment by beyzakokcan** [comment]
Right now, there is not a option to show it. Thats why, my suggestion is to have a option. 
Not "is able", it will be "should be able"

**Comment by hmert** [comment]
Let's give this option to the user? But all editors can see it.

**Comment by beyzakokcan** [comment]
It can be done position based. This option can be added to the position edit page; with "show email adresses"check box in the first version.

**Comment by behramcelen** [comment]
issue can be move to 2.1.1 milestone

**Comment by behramcelen** [comment]
we are not using show email box for now. i  will revise this issue with #1433 issue
