### ISSUE TITLE
Exceptions thrown on some apidoc pages

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1435]
Apidoc pages of recently created endpoints throw the same exception:

> [Semantical Error] The annotation "@JMS\Expose" in property BulutYazilim\LocationBundle\Entity\Province::$country was never imported. Did you maybe forget to add a "use" statement for this annotation? 

Related pages:
- http://dergipark.gov.tr/api/public/v1/doc/articlefile
- http://dergipark.gov.tr/api/public/v1/doc/articleauthor

**Comment by behramcelen** [comment]
This bug fixed with location bundle. With this commit https://github.com/bulutyazilim/LocationBundle/commit/70a57d72c41aef3ace1b80e40a4847c3ec4d289a and we must to publish a new tag.

**Comment by behramcelen** [comment]
I published a new version tagged with v1.0.3 https://github.com/bulutyazilim/LocationBundle/tree/v1.0.3. With a composer update will resolve this issue. I am closing now.
