### ISSUE TITLE
Adding index error

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1440]
Admin-> add a new index
"An exception occurred while executing 'INSERT INTO indexes (id, name, logo, status) VALUES (?, ?, ?, ?)' with params [2, "EconLit", "460f\/10f9\/2490\/5702276630113.png", 1]:

SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "indexes_pkey"
DETAIL: Key (id)=(2) already exists."

**Comment by behramcelen** [comment]
I guess there was an db based auto inc. disease. I fixed to correct count.
