### ISSUE TITLE
Search for One word

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1442]
One word search has some issues;
For example; I search the word "insan"; it gives the result; Journal: İnsanbilim Dergisi
But it should show more results. 
I search "insan ve "; it gives more results; Journals; İnsan ve Toplum Bilimleri Araştırmaları Dergisi, FSM İlmî Araştırmalar İnsan ve Toplum Bilimleri Dergisi, İlmî Araştırmalar: Dil, Edebiyat, Tarih İncelemeleri, HUMANITAS - Uluslararası Sosyal Bilimler Dergisi..
Search works better, for more than one word..

**Comment by behramcelen** [comment]
we will this type issues from this issue https://github.com/ojs/ojs/issues/1447 . so i am closing this issue now
