### ISSUE TITLE
Search- Filters issue

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1443]
First of all, the left panel on the search page; does not look like a filter and I do not get the logic. 
I search; "insan", then I click on the "FSM İlmî Araştırmalar İnsan ve Toplum Bilimleri Dergisi" journal, it does not find any result.  @hmert said; it searches the word "insan" on the journal you have clicked on; "FSM". But when I search "insan" on the "search in the Journal" (on Journal's page), it does show many results; (articles, users..)
How does the filter work?

**Comment by behramcelen** [comment]
we will this type issues from this issue #1447 . so i am closing this issue now
