### ISSUE TITLE
Journal editorial board gives error

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1445]
journal/board gives error. 

Bir hata meydana geldi.
Unexpected "endblock" tag (expecting closing tag for the "if" tag defined near line 33) in OjsSiteBundle::Journal/journal_board.html.twig at line 72.

**Comment by behramcelen** [comment]
fixed with this https://github.com/ojs/ojs/commit/be7d923750270b3203f6b0faf2a52b6bae451015 commit
