### ISSUE TITLE
Publisher delete bug

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1446]
../admin/application/publisher delete not working.

**Comment by behramcelen** [comment]
how not working is throws exception. If throws exception can you paste there

**Comment by beyzakokcan** [comment]
Just not working. It directs you to the homepage and as you go back to check, journal is not deleted.

**Comment by behramcelen** [comment]
@beyzakokcan 
issue title -> `Publisher delete bug`
problem -> `journal is not deleted.` ?

**Comment by beyzakokcan** [comment]
sorry, it is publisher of course.
