### ISSUE TITLE
logo can be removed from journal settings

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1448]
Logo is not shown in anywhere. Journal may have a confusion when they upload and realize it is not shown. So we can remove it.

**Comment by behramcelen** [comment]
@hmert do you agree @beyzakokcan

**Comment by hmert** [comment]
we should show it somewhere. I'll take care of this issue.

**Comment by behramcelen** [comment]
i removed logo field from all journal related forms
