### ISSUE TITLE
Display option in issue edit page 

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1449]
On journal page; on the last issue part;  issue title and issue number and volume (just below) are shown. But issue title is generally issue number and volume. That's why, showing both makes it complicated. http://beta.dergipark/journal/58/issue/1868/edit
We need to add a displaying option to the page and user can choose how to display the issue. 
First: title of the issue should not be mandatory. 
Second: there should be two checkboxes related to display;
       1. display the issue with title only
       2. display the issue with number and volume
When user selects any of them; on journal page; issues and last issue parts will be affected by that option. And also when user enters the issue page; (http://dergipark.beta.dergipark/dergipark-test-dergisi/issue/1868) the issue page also will be displayed according to the selected option. 
(Also Breadcrumb can show the volume and number)

**Comment by beyzakokcan** [comment]
Can you give an update on this issue? At least, can you answer if you get it?

**Comment by utkuaydin** [comment]
I can let the users choose to display either titles or volumes and numbers on public facing pages but I am against making issue titles not mandatory since we would need to modify not only public pages but also other parts of the system and I am not sure if it is worth it.
