### ISSUE TITLE
Add journalId field to routing params automatically via Request journalId param

### ISSUE THREAD

**Issue by behramcelen** [ojs/ojs#1456]
### Describe issue
___________________
We can add journalId field to routing auto. via Routing Listener. We can get journalId from request journalId if exists.

### Related Links
-----------------
https://github.com/ojs/ojs/blob/master/src%2FOjs%2FJournalBundle%2FController%2FArticleFileController.php#L116 etc.

### Related Snippets
------------------
```
'action'  => $this->generateUrl(
                    'ojs_journal_article_file_create',
                    ['journalId' => $journal->getId(), 'articleId' => $article->getId()]
                ),
```

| Q                  | A
| -------------      | ---
| Branch/Tag?        | master
| Bug?               | no
| New feature?       | yes
| Related Issues     |

**Comment by behramcelen** [comment]
@ojs/developers @ojs/owners could you vote this issue.

**Comment by utkuaydin** [comment]
This is not going anywhere.

**Comment by behramcelen** [comment]
@utkuaydin great 👍

**Comment by utkuaydin** [comment]
@behramcelen I still would like to see this implemented. My stance on that didn't change.
