### ISSUE TITLE
References is not always required field

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1460]
### Describe issue
___________________
On submission step

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master" etc. or "2.2" with links
| Bug?               | yes/no
| New feature?       | yes/no
| Related Issues     | comma-separated list of issues

**Comment by behramcelen** [comment]
in my opinion one least citation must be.

**Comment by hmert** [comment]
@behramcelen nope, some type of articles do not have references.

**Comment by beyzakokcan** [comment]
@hmert in our case, at least one citation should be entered as Behram says. Every academic articles should have citations..

**Comment by hmert** [comment]
At the conference, lots of editors have noted that some of paper types (presentations) does not references.

**Comment by hmert** [comment]
I'm closing this issue for God's sake.
