### ISSUE TITLE
Article Keywords Ignored on Api

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1464]
I am sending an article with the data below, api returns success code and I can see the article data in archive except keywords field. Keywords field looks empty. http://i.imgur.com/CIKFPOF.png

Data I am posting: https://gist.github.com/memduhcagridemir/934b31faaf14c681f4aa1f107c795319

I searched article in database(article_translations table) and found the related row. Both title and abstract values are filled with the data I posted, but keywords field was null. 

Here is a screenshot of related database entry: http://i.imgur.com/nX2jhyJ.png

**Comment by memduhcagridemir** [comment]
Same problem occurs on beta server too, 

http://kisi.beta.dergipark.gov.tr/122/issue/1974/22847

**Comment by behramcelen** [comment]
yes you are right. Keyword field is not setting to entity. i am inspecting now

**Comment by behramcelen** [comment]
@memduhcagridemir translations -> keywords field must be array. I revised tests https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Tests/Controller/JournalArticleRestControllerTest.php#L42
