### ISSUE TITLE
Article galley throws exception

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1465]
I am trying to download pdf of an article imported using api. Page throws following exception:

> Catchable Fatal Error: Argument 1 passed to Jb\Bundle\FileUploaderBundle\Service\FileHistoryManager::getUrl() must be an instance of Jb\Bundle\FileUploaderBundle\Entity\FileHistory, null given, called in /data/ojs/src/Ojs/SiteBundle/Controller/DownloadController.php on line 23 and defined 

Link to reproduce: http://kisi.beta.dergipark.gov.tr/123/issue/1975/22851

If I try to download pdf using journal management pages, I can download the pdf. Related management page: http://beta.dergipark.gov.tr/journal/123/article/22851

**Comment by utkuaydin** [comment]
Could you please post the POST request that you are using when creating the file?

**Comment by memduhcagridemir** [comment]
I do not think I can post the entire request here because of the base64 encoded content of file. But this is the overall structure I use.

```
  var fileMeta = {
    file: {
      filename: path.substr(path.lastIndexOf('/') + 1),
      encoded_content: new Buffer(fs.readFileSync(path)).toString('base64')
    },
    type: 0,
    langCode: 1,
    title: 'PDF'
  };
```

According to ojs test here (https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Tests/Controller/JournalArticleFileRestControllerTest.php), I tried with type=2 at first. Then I noticed the article in example journal at OJS sample data, its type was 0 so I changed it to 0.

**Comment by behramcelen** [comment]
@memduhcagridemir can you re-try scenario probably @utkuaydin fixed this issue

**Comment by memduhcagridemir** [comment]
I tried on DergiPark prod server and it still throws exception: 

http://dergipark.gov.tr/journal/890/article/180695/file/160063/show
http://kisi.dergipark.gov.tr/journal-of-strategic-research-in-social-science/issue/17293/180695

**Comment by utkuaydin** [comment]
I don't know when the commit e9ddb87 deployed to that server but it resolves the issue.
