### ISSUE TITLE
Article submission bug

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1467]
### Describe issue
___________________
When you upload two files, the third file is added automatically, and in the 3 step, it gives error that the file should not be blank. 

### Related Links
-----------------
/journal/58/submission/new

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master" 
| Bug?               | yes
| New feature?       | no
| Related Issues     | comma-separated list of issues

**Comment by behramcelen** [comment]
i could not generate problem @beyzakokcan can you support issue with video. and problem is existing really you can reopen issue
