### ISSUE TITLE
Pagination next bug

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1468]
### Describe issue

---

This is a bug that concerns all paginations. 
Clicking on "next" display no next pages, after some point, although there are more pages to be displayed. 
### Related Links

---

for example; on  /journal/{journal_id}/issue, when you click on next you will see the point.. (journal_id=660 as an example)

| Q | A |
| --- | --- |
| Branch/Tag? | "master" |
| Bug? | yes |
| New feature? | no |
| Related Issues | comma-separated list of issues |

**Comment by behramcelen** [comment]
i inspected a few grid and works correctly @beyzakokcan can you support issue with screenshots? i am closing issue now. If you found new problems you can reopen issue

**Comment by beyzakokcan** [comment]
I added a video;
https://drive.google.com/file/d/0B7yJMr_wSCAYN3d3SHJzOXV2QW8/view

**Comment by beyzakokcan** [comment]
@hmert @behramcelen can you reopen?

**Comment by behramcelen** [comment]
I inspected this issue a lot but i can not find problem and solution. if i can not find solution in short term. we can discuss about grid logic.

**Comment by behramcelen** [comment]
this type problems occurs from mysql and pg multiple support logic. With 2.2 milestone we will discuss and we can stop mysql support. If we support only postgresql we can fix all grid based bugs

**Comment by beyzakokcan** [comment]
Problem on the grid still exits.

**Comment by behram** [comment]
related pr https://github.com/ojs/ojs/pull/1648

**Comment by behram** [comment]
i will close this issue after pr merge

**Comment by behram** [comment]
@beyzakokcan this problem solved with related pr
