### ISSUE TITLE
Grid List Ordering bug

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1469]
### Describe issue
___________________
On the pages that includes tables/grid list, for example journal-> issue page, ordering by volumes, it does not give the correct order if the volume has two digits. it orders like 1->10 although there is a 9 between. 

### Related Links
-----------------
journal/{journal_id}/issue 

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master" 
| Bug?               | yes
| New feature?       | no
| Related Issues     | comma-separated list of issues

**Comment by behramcelen** [comment]
we holding issue number and volume fields as string so in db system orders by first digit. We using string because of supporting various features
