### ISSUE TITLE
Issue cover link

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1473]
I can not display issue covers for the issues created by api. Example issue: http://kisi.beta.dergipark.gov.tr/123/issue/1979

I think the link generated for the cover is not correct. This is the link generated by OJS: http://kisi.beta.dergipark.gov.tr/media/cache/resolve/issue_cover_medium/http://beta.dergipark.gov.tr/media/cache/resolve/issue_cover/cee5/952f/69d2/issue-cover-0.jpg

If I try to get http://beta.dergipark.gov.tr/media/cache/resolve/issue_cover/cee5/952f/69d2/issue-cover-0.jpg, I see the cover image I sent.

**Comment by memduhcagridemir** [comment]
Also, if you check the cover image links of issues, they are all the same.  http://kisi.beta.dergipark.gov.tr/123/archive

It generates same cover links for other journals too, http://kisi.beta.dergipark.gov.tr/124/archive

**Comment by behramcelen** [comment]
@memduhcagridemir i only executed `phpunit -c app/ src/Ojs/ApiBundle/Tests/Controller/JournalIssueRestControllerTest.php` test and looked for created issue and works correctly. 
![image](https://cloud.githubusercontent.com/assets/4572080/14691834/2c86d6f8-075c-11e6-85a4-42726198130b.png)
![image](https://cloud.githubusercontent.com/assets/4572080/14691841/3703f2be-075c-11e6-89a0-47429551cc23.png)
you can check https://github.com/ojs/ojs/blob/master/src%2FOjs%2FApiBundle%2FTests%2FController%2FJournalIssueRestControllerTest.php#L48 test action correctly
