### ISSUE TITLE
Mandatory language selection for journal

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1474]
I have created a journal and selected 'English' as mandatory language. You can see the details of journal here: http://beta.dergipark.gov.tr/admin/journal/127/show

If I try to create an issue with only 'English' title, it fails with the json response: https://gist.github.com/memduhcagridemir/62ff5ed9404a6af0535517f9401a1065

If I change the title language to 'Turkish' and submit again, issue gets registered succesfully. 

I think OJS should check the mandatory language of journal before giving validation error for the title field of issue.

**Comment by behramcelen** [comment]
for journal entity validation locale we using system locale (it must be `tr` for *.dergipark.*). if journal has no translation for `tr` locale. you use `-` string for tr translations.

**Comment by memduhcagridemir** [comment]
This issue is not about creating journal, it is about creating issue.

**Comment by behramcelen** [comment]
@memduhcagridemir excuse me. same logic is valid for issue  entity too. 
https://github.com/ojs/ojs/issues/1474#issuecomment-212581682
