### ISSUE TITLE
Filenames and Server Error in API

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1475]
Before https://github.com/ojs/ojs/commit/e9ddb87dab9ce033fc59e699ad8e62f75a52f2ae commit, API was overriding previous pdf files when a file with same filename is passed. This commit made API to return server error(500) thanks to duplicate errors originated by doctrine.

IMHO, API should generate unique filenames for submitted files instead of returning server error, since user cannot determine the cause of server error and he can not guess a filename that is not used. 

In such cases, PKP/OJS generates filenames according to article ids and groups article files under parent journal folder. I think same procedures should be applied to here.

**Comment by behramcelen** [comment]
we generating random path for related files now. You can check from tests.

i am closing issue now. if problem occurs again you can reopen issue or ping to me.
