### ISSUE TITLE
Article galley exception 

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1477]
I did a `git pull` and installed ojs from scratch.

Then ran the article file rest test. One of the tests is failed but it is not the issue I'm concerned now.

After completion of the test, I checked the submitted files. Both files throw exception complaining about file not being where is supposed to be. 

> The file "/path-to-root-of-ojs/app/../web/uploads/article/32ce/771b/07d1/sampleArticleFile.pdf" does not exist 

And this is the same exception I reported 10 days ago in this issue. It contains the link to reproduce the exception: https://github.com/ojs/ojs/issues/1465

I checked the folders there is no `uploads/article/` folder. Instead, related pdfs are stored in `uploads/articlefiles/` folder.

Screenshots: http://imgur.com/a/86ewd

**Comment by utkuaydin** [comment]
Type might be wrong. I pushed the potential fix, could you try it again?

**Comment by memduhcagridemir** [comment]
I made a `git pull` again and run the same test. Another exception is thrown this time. :disappointed: 

> The filename and the fallback cannot contain the "/" and "\" characters.

**Comment by behramcelen** [comment]
I tried and i can not see any problem and recorded a video you can watch from below;
https://drive.google.com/file/d/0Bw64r-lyuwX3eEp1Y1JvZE1iazg/view?usp=sharing

 - My permission command alias;
```
sudo chmod -R 777 app/cache/ app/logs/ app/spool/default
```
 - My clean install file contents;
```
cd /private/var/www/ojs/;
php app/console d:s:d --force;
php app/console ojs:install;
php app/console ojs:install:samples;
php app/console h4cc_alice_fixtures:load:sets;
php app/console ojs:normalize:translatable:objects;
php app/console ojs:mail:events:sync --sync-desc
php app/console dergipark:journal:application:migration
```

If trouble is resumes can you upload an trouble reproduce video via an screen record tool.
You can follow -> https://support.apple.com/en-us/HT201066

**Comment by memduhcagridemir** [comment]
I noticed I did not mentioned where the exception occurs. Exception does not occur when running tests. Tests ran smoothly without fails this time. 

Exception thrown when I browse the pdf from archive pages. I recorded a short video about that.
https://drive.google.com/open?id=0B544f2OjGcn_VTZHYktTU2pIWEk

**Comment by behramcelen** [comment]
issue probably fixed with above commit. @memduhcagridemir can you test again with same scenario. if problem occurs again you can ping us.

**Comment by memduhcagridemir** [comment]
Last commit solves the problem. :+1: 

But I think you havent deployed it to prod server yet. When will it be deployed?

**Comment by behramcelen** [comment]
@memduhcagridemir now i deployed in two beta and prod systems
