### ISSUE TITLE
Makale dosyası hataları

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1478]
Hocam 25 gündür çözülmeyen bir sorunumuz var. Bu issueyu Türkçe yazıyorum ki daha fazla uzamasın bu konu.

Daha önce https://github.com/ojs/ojs/issues/1465 burda açtığım hatayı @utkuaydin nun commiti çözdü. Bu sefer başka bir hata vermeye başladı ojs. (Hatayı da apiden post ederken vermiyor üstelik. POST requestine success dönüyor pdfe ulaşmaya çalıştığımız zaman hata veriyor.) 

O hatayı da https://github.com/ojs/ojs/issues/1477 burada açıkladım. Bu sorunu da @utkuaydin nun commiti çözdü. Committen hemen sonra ojs başka bir hata vermeye başladı. Aynı sorunun devamı olduğunu düşünerek aynı issuenun altına hatayı yazdım. @behramcelen o hatayla ilgilenip https://github.com/ojs/ojs/commit/85aef6cb9982d5c1d0b2b3820951ae45825b6a86 commitini yaptı. 

Bu committen sonra en baştaki hataya geri döndük. Üstelik doğrudan en baştaki hatayı vermiyor, önce başka hata veriyor sayıya ikinci pdf eklendiği zaman ilk hatayı veriyor. İlgili ekran görüntüsünü paylaşıyorum. https://drive.google.com/open?id=0B544f2OjGcn_aFF2bjY0T0hocTA

Burda bir şeyi belirtmek istiyorum. Yukardaki ekran görüntüsünde göreceğiniz ilk hata @behramcelen ın commitiyle çözüldü aslında. Localden baktığım zaman ilk hatayı almıyorum doğrudan pdfi görüyorum. Muhtemelen o commit prod'a deploy edilmedi henüz. Asıl sorunumuz ikinci gelen hata. İkinci hata da sayıya ikinci bir makale ve pdfi eklendiği zaman ortaya çıkıyor.

> Catchable Fatal Error: Argument 1 passed to Jb\Bundle\FileUploaderBundle\Service\FileHistoryManager::getUrl() must be an instance of Jb\Bundle\FileUploaderBundle\Entity\FileHistory, null given, called in /data/ojs_prod/src/Ojs/SiteBundle/Controller/DownloadController.php on line 23 and defined 

Bu hata da https://github.com/ojs/ojs/issues/1465 bunun aynısı.

Bütün bunlar olurken api her istekte başarılı sonuç dönüyor ve ilgili pdflere derginin yönetim sayfalarından(arşiv sayfaları hata veriyor) ulaşabiliyoruz. Bu projenin içinde dp linki paylaşılmasını istemediğiniz için linkleri tekrar paylaşmıyorum ama yukardaki issueların içinden ulaşabilirsiniz. 

Ekran görüntüsünde anlattığım sorunu şöyle de test edebilirsiniz. 
1. /download/article-file/160246
2. /download/article-file/160247
Prod serverında bu urlleri kontrol ederseniz, en son eklenen makalenin(yani 160247), önceki eklenenden farklı hata verdiğiniz göreceksiniz. Sayının içinde 5 makale var, 4tanesi aynı son eklenen farklı hata veriyor. **Tekrarlıyorum, son eklenen makalenin verdiği hata aslında @behramcelen ın commitiyle çözüldü muhtemelen. Asıl sorunumuz ilk 4 makalenin verdiği hata.**

Eğer bizim gönderdiğimiz isteklerde sorun varsa -pdf ve başlığı doğru ulaştığı için sanmıyorum sorun olduğunu- ama yine de varsa, en azından istek gönderirken apinin başarısız olduğunu belirten bir sonuç dönmesini bekleriz. 

Excuse me for writing this issue in Turkish, I needed to express myself clearly because there are more than 70+ journals waiting to be migrated.

**Comment by behramcelen** [comment]
@memduhcagridemir can re-try the scenario probably now above commit solves the problem. If problem is persists you can ping me i can re-open this issue
