### ISSUE TITLE
Ordering ignored on citations

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1479]
I noticed OJS api ignores the "orderNum" field in citation POST request. Citations are sorted in the article page by citation id. 

I think sorting should be done according to "orderNum".

Here is the screencast video: https://drive.google.com/open?id=0B544f2OjGcn_QTNYSjYxMlRaRTA
Related article link: /journal-of-strategic-research-in-social-science/issue/17313/180864

**Comment by behramcelen** [comment]
i inspected issue and api side works correctly. Only we not using order field on template expose. i will use this field on view. So you can use api directly.

**Comment by memduhcagridemir** [comment]
Okay then, thank you :+1:
