### ISSUE TITLE
500 Error on Issue GET Request

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1482]
I'm getting 

> {"error":{"code":500,"message":"Internal Server Error"}}

as response when I make a GET request to prod server.

You can reproduce the issue using curl:
> $ curl -XGET "http://dergipark.gov.tr/api/v1/journal/894/issues/new.json?apikey=XYZ"

More detailed response with app_dev.php;

> {"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"Error: Call to a member function getInPress() on a non-object","class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/data\/ojs_prod\/src\/Ojs\/JournalBundle\/Form\/Type\/IssueType.php","line":157,"args":[]}]}]}}

**Comment by hmert** [comment]
@memduhcagridemir I've removed the apikKey.

**Comment by behramcelen** [comment]
@utkuaydin probably this issue about new in press logic. this is exception output http://www.jsoneditoronline.org/?id=cc539b77c2c1874df19578f22ce7a3f3

**Comment by utkuaydin** [comment]
Commit a8b823c is a quick workaround for that error although the underlying issue is probably something different because those variables are supposed to be instances of `Issue` class.

**Comment by behramcelen** [comment]
i re-tested and now works correctly.

**Comment by behramcelen** [comment]
probably this https://github.com/ojs/ojs/commit/a8b823cf09e17426e721423acf7d977184fc43ed commit solved problem
