### ISSUE TITLE
Check statuses of content before displaying them publicly

### ISSUE THREAD

**Issue by utkuaydin** [ojs/ojs#1490]
### Description
___________________
Journals, issues and articles can be accessed publicly regardless of their status.

| Q                  | A
| -------------      | ---
| Branch/Tag?        | master
| Bug?               | yes
| New feature?       | no

**Comment by behramcelen** [comment]
related issue https://github.com/ojs/ojs/issues/1413

**Comment by behramcelen** [comment]
and user profile logic too
