### ISSUE TITLE
Server error on institution post request

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1491]
I'm getting 

```
{
  "error": {
    "code": 500,
    "message": "Internal Server Error"
  }
}
```

error when I make post request to `/api/v1/institutions.json` endpoint on prod server. 

This is the command I use;
```
$ curl -H "Content-Type: application/json" -XPOST --data '{"name": "Yeditepe University, Faculty of Commerce"}' http://dergipark.gov.tr/api/v1/institutions.json?apikey=XYZ

{"error":{"code":500,"message":"Internal Server Error"}}
```

A short video of same request with postman: https://drive.google.com/open?id=0B544f2OjGcn_WWtUQjRPaW9PSFU

**Comment by behramcelen** [comment]
we changed publisher form type a little you can follow from https://github.com/ojs/ojs/blob/master/src/Ojs/AdminBundle/Form/Type/PublisherType.php. 
I revised tests at same time and checked tests works correctly.
You can checks from https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Tests/Controller/PublisherRestControllerTest.php

If problem persists you can re-open issue or ping me.

**Comment by memduhcagridemir** [comment]
This issue is not about publisher requests. I am trying to add author institution with `/api/v1/institutions.json` endpoint.

I checked institution schema using `/api/v1/institutions/new.json` endpoint and it looks the same.

**Comment by behramcelen** [comment]
@memduhcagridemir excuse me my messy head 😕  i will inspect institution logic

**Comment by behramcelen** [comment]
problem causes from db side output like 
```
An exception occurred while executing 'INSERT INTO institution (id, lft, rgt, root, lvl, name, address, city, address_lat, address_long, phone, fax, email, domain, url, wiki, logo, header, created, updated, deletedAt, createdBy, updatedBy, tags, institution_type_id, country_id, parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [167, 0, 0, 0, 0, \"Yeditepe University, Faculty of Commerce\", null, null, null, null, null, null, null, null, null, null, null, null, \"2016-05-24 02:43:08\", \"2016-05-24 02:43:08\", null, \"\", \"\", \"\", null, null, null]:\n\nSQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"institution_pkey\"\nDETAIL:  Key (id)=(167) already exists.
```
an auto increment problem i can not figure out problem we can discuss it with @hmert.
There is 286 entry on table but doctrine or pg giving unique id as 16* i can not get it.

**Comment by behramcelen** [comment]
i solved problem via `ALTER SEQUENCE institution_id_seq RESTART WITH 287;` command. I tried  to creating a new institution and any problem occured. @memduhcagridemir can you re-try probably you can success now.
