### ISSUE TITLE
Export Data

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1493]
Journal Manager can export their data

- [ ] XML/JSON structured data

- [ ] DOAJ/CrossRef style export /cc @beyzakokcan 

https://doaj.org/features

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "2.2"
| Bug?               | no
| New feature?       | yes

**Comment by behramcelen** [comment]
development continues on https://github.com/ojs/ojs/tree/iss1493 branch

**Comment by behramcelen** [comment]
needs more description
