### ISSUE TITLE
API:Nelmio Bug

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1520]
`Unknown "getApiViews" function in NelmioApiDocBundle::layout.html.twig at line 699. `

### Related Links
-----------------
/api/public/v1/doc

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "2.2"
| Bug?               | yes
| New feature?       | no

**Comment by behramcelen** [comment]
fixed with ojs/export-bundle https://github.com/ojs/ExportBundle/commit/5b6c23e6b447105d2fc00206d97952ad8b689f63
