### ISSUE TITLE
Check statuses of Publisher, Journal, Issue, Article, User before displaying them publicly

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1526]
@beyzakokcan will address the status codes for all of them.

### Related Links
-----------------
#1490 

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "2.3"
| Bug?               | yes
| New feature?       | no

**Comment by behramcelen** [comment]
@beyzakokcan can you check https://github.com/ojs/ojs/issues/1490 issue and drop related links here which have problem. 

If there is no problem @hmert can you close this issue

**Comment by behramcelen** [comment]
i am closing this issue probably no one wil check this issue. i checked and there is no problem
