### ISSUE TITLE
Author Search is not functional for finding articles

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1527]
### Related Links
-----------------

`http://dergipark.gov.tr/search?q=%22mustafa+k%C4%B1l%C4%B1%C3%A7arslan%22&section=author`

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "2.3"
| Bug?               | yes
| New feature?       | no

**Comment by behramcelen** [comment]
https://github.com/ojs/ojs/blob/master/app/config/elastica.yml#L137
https://github.com/ojs/ojs/blob/master/app/config/elastica.yml#L307
we must  to prevent elastic index that author which not belongs to any article.

**Comment by behramcelen** [comment]
i am assigned this issue to @yazbahar
