### ISSUE TITLE
Internal Server Error on Journal GET Request

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1534]
OJS returns server error to journal get requests. This endpoint was working properly before. It started giving errors yesterday.

$ curl -XGET http://dergipark.gov.tr/api/v1/journals/1120.json?apikey=XXX
{"error":{"code":500,"message":"Internal Server Error"}}

**Comment by hmert** [comment]
@memduhcagridemir It's because of a big DB dump. Now, I separate the production db from bulk import db.

it's fixed now.
