### ISSUE TITLE
OJS throws same exception on different pages

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1540]
OJS returns 500 to api calls and throws same exception on several pages.

URL: /admin/journal/
> An exception occurred while executing 'SELECT t0.id AS id_1, t0.title_transliterated AS title_transliterated_2, t0.path AS path_3, t0.domain AS domain_4, t0.issn AS issn_5, t0.total_article_view AS total_article_view_6, t0.total_article_download AS total_article_download_7, t0.eissn AS eissn_8, t0.founded AS founded_9, t0.ending_date AS ending_date_10, t0.url AS url_11, t0.address AS address_12, t0.phone AS phone_13, t0.email AS email_14, t0.status AS status_15, t0.access_model AS access_model_16, t0.image AS image_17, t0.journal_indexes_bag AS journal_indexes_bag_18, t0.header AS header_19, t0.logo AS logo_20, t0.languageCodeSet AS languagecodeset_21, t0.google_analytics_id AS google_analytics_id_22, t0.slug AS slug_23, t0.is_configured AS is_configured_24, t0.created AS created_25, t0.updated AS updated_26, t0.deletedAt AS deletedat_27, t0.createdBy AS createdby_28, t0.updatedBy AS updatedby_29, t0.tags AS tags_30, t0.setup_finished AS setup_finished_31, t0.footer_text AS footer_text_32, t0.note AS note_33, t0.view_count AS view_count_34, t0.download_count AS download_count_35, t0.printed AS printed_36, t0.publisher_id AS publisher_id_37, t0.theme_id AS theme_id_38, t0.design_id AS design_id_39, t0.country_id AS country_id_40, t0.mandatory_lang_id AS mandatory_lang_id_41 FROM journal t0 WHERE t0.id = ? AND ((t0.deletedAt IS NULL))' with params [589]:
SQLSTATE[42703]: Undefined column: 7 ERROR: column t0.total_article_download does not exist
LINE 1: ...5, t0.total_article_view AS total_article_view_6, t0.total_a...

URL: /{journalSlug}
> An exception occurred while executing 'SELECT t0.id AS id_1, t0.title_transliterated AS title_transliterated_2, t0.path AS path_3, t0.domain AS domain_4, t0.issn AS issn_5, t0.total_article_view AS total_article_view_6, t0.total_article_download AS total_article_download_7, t0.eissn AS eissn_8, t0.founded AS founded_9, t0.ending_date AS ending_date_10, t0.url AS url_11, t0.address AS address_12, t0.phone AS phone_13, t0.email AS email_14, t0.status AS status_15, t0.access_model AS access_model_16, t0.image AS image_17, t0.journal_indexes_bag AS journal_indexes_bag_18, t0.header AS header_19, t0.logo AS logo_20, t0.languageCodeSet AS languagecodeset_21, t0.google_analytics_id AS google_analytics_id_22, t0.slug AS slug_23, t0.is_configured AS is_configured_24, t0.created AS created_25, t0.updated AS updated_26, t0.deletedAt AS deletedat_27, t0.createdBy AS createdby_28, t0.updatedBy AS updatedby_29, t0.tags AS tags_30, t0.setup_finished AS setup_finished_31, t0.footer_text AS footer_text_32, t0.note AS note_33, t0.view_count AS view_count_34, t0.download_count AS download_count_35, t0.printed AS printed_36, t0.publisher_id AS publisher_id_37, t0.theme_id AS theme_id_38, t0.design_id AS design_id_39, t0.country_id AS country_id_40, t0.mandatory_lang_id AS mandatory_lang_id_41 FROM journal t0 WHERE t0.slug = ? AND t0.status = ? AND ((t0.deletedAt IS NULL)) LIMIT 1' with params ["eibd", 1]:
SQLSTATE[42703]: Undefined column: 7 ERROR: column t0.total_article_download does not exist
LINE 1: ...5, t0.total_article_view AS total_article_view_6, t0.total_a...

**Comment by hmert** [comment]
fixed

**Comment by behram** [comment]
this issue is not code related :bug: we updated the doctrine schema and fixed.
