### ISSUE TITLE
Articles send from API does not shown in archive

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1547]
The issue and articles below are sent using API.

Articles and issues are created successfully but there is another problem.

There should be articles in this issue: /journal/1352/issue/23896/article 
It is empty as in /bilig/issue/23896 page also.

/journal/1352/issue/23896/arrange is the article arrange page of the same issue. There are articles in this page. These articles should be shown in other pages also.

Screencast: https://goo.gl/k6j6u2

**Comment by behram** [comment]
@memduhcagridemir your problem probably will be solved via this https://github.com/ojs/ojs/pull/1571 pr. And we fixed related for deployed systems (There is no BC for now). Can you check again after pr merge and system deploy(~24 hour.)
