### ISSUE TITLE
Catalog

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1559]
- [x]  Journal, article and author should have a catalog id(s)

- [x]  Catalog is global

- [ ] SiteBundle should filter items by catalog on be half of request's domain.

 

| Q                  | A
| -------------      | ---
| Branch/Tag?        | "master" 
| Bug?               | no
| New feature?       | yes

**Comment by behram** [comment]
we can follow development from https://github.com/ojs/ojs/tree/feature/object-catalog branch

**Comment by behram** [comment]
this branch https://github.com/ojs/ojs/tree/feature/object-catalog is deprecated fully. i will make related changes under this https://github.com/ojs/ojs/compare/feature/object-catalog-2 branch. 

i will remove https://github.com/ojs/ojs/tree/feature/object-catalog branch

**Comment by behram** [comment]
issue resolved with related pr. item 3 will be done with another issue.
