### ISSUE TITLE
Contact-Type is doubled at grid

### ISSUE THREAD

**Issue by hmert** [ojs/ojs#1576]
![image](https://cloud.githubusercontent.com/assets/182906/19257293/068252d6-8f77-11e6-971d-5807c4c04491.png)

| Q                  | A
| -------------      | ---
| Branch/Tag?        |  "2.2"
| Bug?               | yes
| New feature?       | no

**Comment by behram** [comment]
fixed with https://github.com/ojs/ojs/pull/1586
