### ISSUE TITLE
Admin stats issue page error

### ISSUE THREAD

**Issue by behram** [ojs/ojs#1612]
### Describe issue

---

Throws exception on admin stats issue page
### Exception Output

---

`Type error: Argument 1 passed to Ojs\JournalBundle\Service\JournalService::generateUrl() must be an instance of Ojs\JournalBundle\Entity\Journal, null given, called in /data/ojs_prod/src/Ojs/CoreBundle/Service/Twig/OjsExtension.php on line 199`
### Related Links

---

`/admin/stats/issue`

| Q | A |
| --- | --- |
| Branch/Tag? | "master" etc. or "2.2" with links |
| Bug? | yes/no |
| New feature? | yes/no |

**Comment by behram** [comment]
and @yazbahar can you add all admin stats pages phpunit support

**Comment by behram** [comment]
@yazbahar did you fixed this issue

**Comment by behram** [comment]
@yazbahar please close this issue if fixed 🙏  or give an comment 😄

**Comment by hmert** [comment]
fixed
