### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by samanmohamadi** [ojs/ojs#1621]
Hi, my installed elasticsearch version is 2.4.1 wich is not supported by ruflin/elastica v2.3 (required by bulutyazilim/FOSElasticaBundle). 
Is there any way to use elasticsearch v2.x with this ojs ?

Thanks

**Comment by behram** [comment]
unfortunally, FOSElasticaBundle only supports <2.0. because of that we suggesting `1.7.4` version of elasticsearch. 

We using a lot of deprecated functions of 2.0.

**Comment by samanmohamadi** [comment]
ِYou'r right But, currently original repo ( FriendsOfSymfony/FOSElasticaBundle ) supports 2.x  versions.

**Comment by hmert** [comment]
hi @samanmohamadi, I'm following https://github.com/ruflin/Elastica/issues/1184 this issue for upgrading. If they support 5.x and release it as a LTS, we will upgrade.

BTW, thank you for your interest. Have you deploy ojs for testing or production?

**Comment by samanmohamadi** [comment]
Hi @hmert, I have been tracking this repo for nearly 6 months.
I want to test it and if it suits our needs use it in production, Unfortunately because I have elasticsearch v2.4 installed (which is required by other projects that I'm working on) I can't test it right now.
Thank you for your great works.

**Comment by hmert** [comment]
@samanmohamadi let me help you to run and use it on production.

We're glad to see it publicly if it is available.

**Comment by samanmohamadi** [comment]
Thank You, I  will deploy it for production as soon as possible, And I will inform you then. 
Thanks
