### ISSUE TITLE
Citation parsing via citation extraction services

### ISSUE THREAD

**Issue by beyzakokcan** [ojs/ojs#1649]
Editor should check the raw citations against the external databases; such as WorldCat, ISBNdb, PubMed and others, for accuracy.

CITATION PARSING
To find and check citations in citation databases they first have to be split into machine readable metadata: title, publisher, publication date, etc. must all be extracted from the original citation text provided by the author. In other words; editors should parse the citations entered by author in the article submission step, using the citation extraction services; FreeCite, RegEx, ParsCit, ParaCite

CITATION CHECKING
Then editors should be able to configure connections to external citation databases. This will help editors to find errors in authors' citations or add additional information (e.g. DOIs or PubMed IDs) required for electronic publishing or deposit. These external citation databases are PubMed, CrossRef and ISBNdb. Some of these databases require registration or configuration information to be entered. So you will just make sure the editors are able to do the configuration.

**Comment by hmert** [comment]
@mirunakyuz will handle this issue

**Comment by beyzakokcan** [comment]
PKP/OJS citation markup assistant can assist. I recommend you to build pkp/ojs as well.
Help docs;

https://groups.google.com/forum/#!topic/libpub/NOIUuE4kn4U
http://pkp.sfu.ca/ojs/docs/userguide/2.3.3/journalManagementSetup3.html#journalManagementSetup3-7
https://pkp.sfu.ca/wiki/index.php?title=Citation_Markup_Assistant_testing

OJS example journal that uses the assistant; http://www.journals.istanbul.edu.tr/iudis/manager/setup/3

**Comment by hmert** [comment]
- [x] PARSING

- [x]  DOI

All done, markdown is not required for now and future..

**Comment by hmert** [comment]
@mirunakyuz very good job 👍
