### ISSUE TITLE
Importing Article Statistics

### ISSUE THREAD

**Issue by memduhcagridemir** [ojs/ojs#1696]
Hello,

I need to import some article statistics (such as download count and article visit count) along with the article using the API.

Does the current API support this? If yes, can you show me the related apidoc page? If not, can you add this feature to API?

Thank you

**Comment by beyzakokcan** [comment]
@hmert this issue is important. We need to import the previous stats for each article.

**Comment by hmert** [comment]
@memduhcagridemir after next deployment you may use statistics parameters on API
